name: political_trend_predictor
description: "A Flutter project for predicting political trends using AI and news data."
publish_to: 'none' # Private package

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  http: ^1.2.2  # http paketini güncelleyerek çözüm
  syncfusion_flutter_charts: ^20.4.38  # en son sürüm numarasını kullanın
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Uncomment and add asset files if needed
  # assets:
  #   - images/sample_image.png

  # Uncomment and configure custom fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
